## Artificial Neural Network

#### Importing the libraries

In [1]:
import numpy as np 
import pandas as pd 
import tensorflow as tf 

### Data Preprocessing

#### Importing the dataset

In [2]:
dataset = pd.read_csv('2_Folds5x2_pp.csv')
dataset.head()

AT      V       AP     RH      PE
0  14.96  41.76  1024.07  73.17  463.26
1  25.18  62.96  1020.04  59.08  444.37
2   5.11  39.40  1012.16  92.14  488.56
3  20.86  57.32  1010.24  76.64  446.48
4  10.82  37.50  1009.23  96.62  473.90

In [3]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9568 entries, 0 to 9567
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   AT      9568 non-null   float64
 1   V       9568 non-null   float64
 2   AP      9568 non-null   float64
 3   RH      9568 non-null   float64
 4   PE      9568 non-null   float64
dtypes: float64(5)
memory usage: 373.9 KB


In [4]:
dataset.isnull().sum()

AT    0
V     0
AP    0
RH    0
PE    0
dtype: int64

In [5]:
dataset.describe()

AT            V           AP           RH           PE
count  9568.000000  9568.000000  9568.000000  9568.000000  9568.000000
mean     19.651231    54.305804  1013.259078    73.308978   454.365009
std       7.452473    12.707893     5.938784    14.600269    17.066995
min       1.810000    25.360000   992.890000    25.560000   420.260000
25%      13.510000    41.740000  1009.100000    63.327500   439.750000
50%      20.345000    52.080000  1012.940000    74.975000   451.550000
75%      25.720000    66.540000  1017.260000    84.830000   468.430000
max      37.110000    81.560000  1033.300000   100.160000   495.760000

In [6]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [7]:
print(X)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]


In [8]:
print(y)

[463.26 444.37 488.56 ... 429.57 435.74 453.28]


#### Splitting the dataset into the Training and Test set 

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

### Building the ANN

#### Initializing the ANN

In [10]:
ann = tf.keras.models.Sequential()

#### Adding the input layer and the first hidding layer

In [11]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

#### Adding the second hidding layer

In [12]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

#### Adding the output layer

In [13]:
ann.add(tf.keras.layers.Dense(units=1))

### Training the ANN

#### Compiling the ANN

In [14]:
ann.compile(optimizer='adam', loss='mean_squared_error')

#### Training the ANN on the Training set

In [15]:
ann.fit(X_train, y_train, batch_size=32, epochs=100)

Epoch 1/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 896us/step - loss: 724334.3125
Epoch 2/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 964us/step - loss: 331471.8125
Epoch 3/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 877us/step - loss: 247688.0000
Epoch 4/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 934us/step - loss: 123986.5781
Epoch 5/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 104.8257
Epoch 6/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 104.0400  
Epoch 7/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 902us/step - loss: 100.2315
Epoch 8/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 847us/step - loss: 94.3330
Epoch 9/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 939us/step - loss: 94.0414
Epoch 10/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 833us/step - loss: 92.9181
Epoch 11/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 831us/step - loss: 86.2290
Epoch 12/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 851us/step - loss: 81.5610
Epoch 13/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 849us/step - loss: 78.0445
Epoch 14/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 906us/step 

#### Predicting the Test set results

In [17]:
y_pred = ann.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test), 1)), 1))

60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step  
[[431.47 431.23]
 [462.52 460.01]
 [466.01 461.14]
 ...
 [473.27 473.26]
 [440.02 438.  ]
 [459.26 463.28]]
